stages:
  - test
  - build
  - deploy


lint-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 parks_api
    - flake8 accounts_api


api-unit-test-job:
  image: python:3-bullseye
  stage: test
  needs:
    - lint-test-job
  script:
    - cd accounts_api
    - pip install -r requirements.txt
    - python -m pytest tests/


build-front-end-job:
  stage: build
  image: node:lts-bullseye
  needs:
    - lint-test-job
    - api-unit-test-job
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/


pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
