
volumes:
  mongo-data:
      external: false
services:
  mongo:
    image: mongo:5
    volumes:
        - mongo-data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    build:
      context: setup/mongo-express
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
  parks-api:
    build:
      context: parks_api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./parks_api:/app
  accounts-api:
      build:
          context: ./accounts_api
          dockerfile: ./Dockerfile.dev
      ports:
          - "8001:8000"
      volumes:
          - ./accounts_api:/app
      environment:
        DATABASE_URL: mongodb://root:password@mongo/admin
        SIGNING_KEY: 87fe4a3fcfb60092dbaeb854a196bc3d9b190aed7930c734749e85245de698420c25f8e6899c421b4494e99459e01058de5daa9d49584cd62ec975da9aea33da
        DATABASE_NAME: db-name
        WAIT_HOSTS: mongo:27017
        WAIT_BEFORE: 5
        WAIT_TIMEOUT: 60

  react-frontend:
    image: node:lts-bullseye
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
      WATCHPACK_POLLING: true
      REACT_APP_API_HOST: http://localhost:8001
      REACT_APP_WS_HOST: ws://localhost:8001
